#ifndef __EVENTTYPE_H
#define __EVENTTYPE_H

/*!
	A list of all possible Events within the Game
*/
enum EventType
{
	ALL_EVENTS,
	TEST_EVENT,
	GAME_INITIALIZED,
	GAME_LEVEL_CHANGED,
	GAME_QUIT,
	GAME_ENDED,
	INPUT_KEY_UP,
	INPUT_KEY_DOWN,
	INPUT_MOUSE_PRESSED,
	INPUT_MOUSE_RELEASED,
	INPUT_MOUSE_MOVED,
	GRAPHICS_SETTINGS_CHANGED,
	UI_TITLE_SCREEN,
	UI_MAIN_MENU,
	UI_PAUSE_MENU,
	UI_OPTIONS,
	UI_CLEAR,
	UI_CONSOLE,
	LOG_MESSAGE_APPENDED,
	SCRIPT_COMMAND_EXECUTED,
	EVENTTYPE_MAX

};

#endif
